// backend/src/models/Transaction.js
import mongoose from "mongoose";

const transactionSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    type: {
      type: String,
      enum: ["income", "expense"],
      required: true,
    },

    amount: {
      type: Number,
      required: true,
      min: 0.01,
    },

    category: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Category",
      required: true,
    },

    note: {
      type: String,
      trim: true,
      maxlength: 200,
      default: "",
    },

    date: {
      type: Date,
      default: Date.now,
      validate: {
        validator: function (value) {
          return value <= new Date();
        },
        message: "Date cannot be in the future",
      },
    },

    paymentMethod: {
      type: String,
      enum: ["cash", "upi", "card", "bank"],
      default: "upi",
    },

    // ─── Idempotency key ─────────────────────────────────────────────────────
    // Set only when a Transaction is auto-generated by the recurring cron job.
    // Combined with the sparse unique index below, this prevents the scheduler
    // from creating duplicate transactions for the same recurring rule on the
    // same calendar day — even if the process crashes and retries, or if two
    // cron instances fire concurrently.
    //
    // NEVER set this field through the user-facing API — the Joi validator
    // in transaction.validator.js does not allow it, so only the cron job
    // can write it.
    sourceRecurringId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "RecurringTransaction",
      default: null,
    },
  },
  { timestamps: true },
);

// ─── Indexes ─────────────────────────────────────────────────────────────────

// Primary query: user + date (most common — list & sort by date)
transactionSchema.index({ user: 1, date: -1 });

// Filter by type within a user
transactionSchema.index({ user: 1, type: 1, date: -1 });

// Filter by category within a user
transactionSchema.index({ user: 1, category: 1, date: -1 });

// Combined type + category filter
transactionSchema.index({ user: 1, type: 1, category: 1, date: -1 });

// Amount-based sorting
transactionSchema.index({ user: 1, amount: -1 });

// createdAt-based ordering (fallback / admin)
transactionSchema.index({ user: 1, createdAt: -1 });

// ─── Idempotency index ────────────────────────────────────────────────────────
// sparse: true  → only documents where sourceRecurringId is non-null are
//                 indexed.  Manual transactions (null) are excluded entirely,
//                 so this index has zero effect on normal API usage.
// unique: true  → two cron writes for the same (recurring rule, date) pair
//                 will always result in one success and one duplicate-key
//                 error (code 11000), which the scheduler catches gracefully.
//
// The `date` stored by the scheduler is always midnight-normalised
// (today.setHours(0,0,0,0)), so the uniqueness boundary is exactly one
// calendar day per recurring rule.
transactionSchema.index(
  { sourceRecurringId: 1, date: 1 },
  {
    unique: true,
    sparse: true,
    name: "recurring_idempotency_idx",
  },
);

export default mongoose.model("Transaction", transactionSchema);
